const prisma = require("../lib/prisma");

async function main() {
  console.log("Seeding services...");

  // Clear existing data (dev only)
  await prisma.service.deleteMany();

  const services = [
    {
      name: "Downtown Community Health Centre",
      address: "123 Queen St W",
      city: "Toronto",
      category: "Health",
      phone: "416-555-1001",
      website: "https://example-health-toronto.ca",
      postalCode: "M5H 2M9",
      latitude: 43.65107,
      longitude: -79.347015,
    },
    {
      name: "Parkdale Community Legal Clinic",
      address: "220 Cowan Ave",
      city: "Toronto",
      category: "Legal",
      phone: "416-555-2002",
      website: "https://example-legal-parkdale.ca",
      postalCode: "M6K 2N6",
      latitude: 43.639,
      longitude: -79.4305,
    },
    {
      name: "Eastside Food Bank",
      address: "45 Main St",
      city: "Hamilton",
      category: "Food Bank",
      phone: "905-555-3003",
      website: "",
      postalCode: "L8H 1A1",
      latitude: 43.2557,
      longitude: -79.8711,
    },
    {
      name: "Ottawa Community Housing Resource Centre",
      address: "750 Somerset St W",
      city: "Ottawa",
      category: "Housing",
      phone: "613-555-4004",
      website: "ottawa-housing-example.ca",
      postalCode: "K1R 6P9",
      latitude: 45.4215,
      longitude: -75.6972,
    },
    {
      name: "North York Youth Employment Hub",
      address: "10 Finch Ave W",
      city: "Toronto",
      category: "Employment",
      phone: "416-555-5005",
      website: "",
      postalCode: "M2N 6L9",
      latitude: 43.7805,
      longitude: -79.4156,
    },
    {
      name: "Scarborough Women's Shelter",
      address: "Confidential Location",
      city: "Toronto",
      category: "Shelter",
      phone: "416-555-6006",
      website: "",
      postalCode: "M1P 4X1",
      latitude: 43.7735,
      longitude: -79.251,
    },
    {
      name: "Waterloo Newcomer Settlement Centre",
      address: "55 King St S",
      city: "Waterloo",
      category: "Settlement",
      phone: "519-555-7007",
      website: "https://waterloo-newcomers-example.ca",
      postalCode: "N2J 1P2",
      latitude: 43.4643,
      longitude: -80.5204,
    },
    {
      name: "Mississauga Seniors Recreation Centre",
      address: "100 Lakeshore Rd W",
      city: "Mississauga",
      category: "Seniors",
      phone: "905-555-8008",
      website: "",
      postalCode: "L5H 1G3",
      latitude: 43.5527,
      longitude: -79.5937,
    },
    {
      name: "Downtown Toronto Public Library Branch",
      address: "789 Yonge St",
      city: "Toronto",
      category: "Library",
      phone: "416-555-9009",
      website: "torontopubliclibrary.ca",
      postalCode: "M4W 2G8",
      latitude: 43.6712,
      longitude: -79.3868,
    },
    {
      name: "Kingston Mental Health Support Centre",
      address: "300 Princess St",
      city: "Kingston",
      category: "Mental Health",
      phone: "613-555-1010",
      website: "",
      postalCode: "K7L 1B4",
      latitude: 44.2312,
      longitude: -76.486,
    },
    {
      name: "Downtown Community Health Centre",
      category: "Health",
      address: "120 King St W",
      city: "Toronto",
      postalCode: "M5H 1A9",
      phone: "416-555-0101",
      website: "https://example.org/downtown-health",
      latitude: 43.6487,
      longitude: -79.3854,
    },
    {
      name: "Harbourfront Mental Wellness Clinic",
      category: "Mental Health",
      address: "250 Queens Quay W",
      city: "Toronto",
      postalCode: "M5J 2N5",
      phone: "416-555-0102",
      website: "https://example.org/harbourfront-mental-health",
      latitude: 43.6396,
      longitude: -79.3806,
    },
    {
      name: "West End Housing Support Services",
      category: "Housing",
      address: "45 Dufferin St",
      city: "Toronto",
      postalCode: "M6K 3C3",
      phone: "416-555-0103",
      website: "https://example.org/west-end-housing",
      latitude: 43.6365,
      longitude: -79.4229,
    },
    {
      name: "Parkdale Overnight Shelter",
      category: "Shelter",
      address: "310 Queen St W",
      city: "Toronto",
      postalCode: "M5V 2A2",
      phone: "416-555-0104",
      website: "https://example.org/parkdale-shelter",
      latitude: 43.6499,
      longitude: -79.3948,
    },
    {
      name: "Eastside Food Bank",
      category: "Food Bank",
      address: "12 Danforth Ave",
      city: "Toronto",
      postalCode: "M4K 1M5",
      phone: "416-555-0105",
      website: "https://example.org/eastside-food-bank",
      latitude: 43.6766,
      longitude: -79.358,
    },
    {
      name: "Regent Adult Learning Centre",
      category: "Education",
      address: "55 Parliament St",
      city: "Toronto",
      postalCode: "M5A 3H7",
      phone: "416-555-0106",
      website: "https://example.org/regent-adult-learning",
      latitude: 43.6514,
      longitude: -79.3616,
    },
    {
      name: "Riverdale Child Care Co-operative",
      category: "Child Care",
      address: "90 Broadview Ave",
      city: "Toronto",
      postalCode: "M4M 0A7",
      phone: "416-555-0107",
      website: "https://example.org/riverdale-child-care",
      latitude: 43.6581,
      longitude: -79.3516,
    },
    {
      name: "Golden Years Seniors Centre",
      category: "Seniors",
      address: "22 Bloor St E",
      city: "Toronto",
      postalCode: "M4W 1A9",
      phone: "416-555-0108",
      website: "https://example.org/golden-years",
      latitude: 43.671,
      longitude: -79.3867,
    },
    {
      name: "North York Employment Resource Hub",
      category: "Employment",
      address: "5000 Yonge St",
      city: "Toronto",
      postalCode: "M2N 7E9",
      phone: "416-555-0109",
      website: "https://example.org/northyork-employment",
      latitude: 43.768,
      longitude: -79.412,
    },
    {
      name: "Downtown Community Legal Clinic",
      category: "Legal",
      address: "720 Bay St",
      city: "Toronto",
      postalCode: "M5G 2K1",
      phone: "416-555-0110",
      website: "https://example.org/downtown-legal",
      latitude: 43.6604,
      longitude: -79.385,
    },
    {
      name: "Lakeshore Recreation Centre",
      category: "Recreation",
      address: "350 Kipling Ave",
      city: "Toronto",
      postalCode: "M8V 3L2",
      phone: "416-555-0111",
      website: "https://example.org/lakeshore-rec",
      latitude: 43.6044,
      longitude: -79.5202,
    },
    {
      name: "Queen Street Public Library",
      category: "Library",
      address: "220 Queen St E",
      city: "Toronto",
      postalCode: "M5A 1S3",
      phone: "416-555-0112",
      website: "https://example.org/queen-library",
      latitude: 43.6533,
      longitude: -79.3696,
    },
    {
      name: "Cedarvale Community Centre",
      category: "Community Centre",
      address: "180 Vaughan Rd",
      city: "Toronto",
      postalCode: "M6C 2L8",
      phone: "416-555-0113",
      website: "https://example.org/cedarvale-community",
      latitude: 43.6895,
      longitude: -79.4254,
    },
    {
      name: "Newcomer Settlement Services Toronto",
      category: "Settlement",
      address: "100 Immigration Way",
      city: "Toronto",
      postalCode: "M1P 4K7",
      phone: "416-555-0114",
      website: "https://example.org/toronto-settlement",
      latitude: 43.773,
      longitude: -79.258,
    },

    // Ottawa
    {
      name: "Centretown Community Health Centre",
      category: "Health",
      address: "420 Bank St",
      city: "Ottawa",
      postalCode: "K2P 1Y8",
      phone: "613-555-0201",
      website: "https://example.org/centretown-health",
      latitude: 45.4128,
      longitude: -75.695,
    },
    {
      name: "Rideau Mental Health Walk-in Clinic",
      category: "Mental Health",
      address: "75 Rideau St",
      city: "Ottawa",
      postalCode: "K1N 5W4",
      phone: "613-555-0202",
      website: "https://example.org/rideau-mental-health",
      latitude: 45.427,
      longitude: -75.69,
    },
    {
      name: "Ottawa Housing Help Centre",
      category: "Housing",
      address: "120 Slater St",
      city: "Ottawa",
      postalCode: "K1P 5H2",
      phone: "613-555-0203",
      website: "https://example.org/ottawa-housing-help",
      latitude: 45.4205,
      longitude: -75.6996,
    },
    {
      name: "Market Street Emergency Shelter",
      category: "Shelter",
      address: "15 ByWard Market Sq",
      city: "Ottawa",
      postalCode: "K1N 9B7",
      phone: "613-555-0204",
      website: "https://example.org/market-shelter",
      latitude: 45.4273,
      longitude: -75.6931,
    },
    {
      name: "Vanier Community Food Cupboard",
      category: "Food Bank",
      address: "290 Montreal Rd",
      city: "Ottawa",
      postalCode: "K1L 6B8",
      phone: "613-555-0205",
      website: "https://example.org/vanier-food",
      latitude: 45.4315,
      longitude: -75.6607,
    },
    {
      name: "Algonquin Adult Learning and Skills Centre",
      category: "Education",
      address: "1385 Woodroffe Ave",
      city: "Ottawa",
      postalCode: "K2G 1V8",
      phone: "613-555-0206",
      website: "https://example.org/algonquin-skills",
      latitude: 45.3484,
      longitude: -75.7546,
    },
    {
      name: "Orléans Early Learning Centre",
      category: "Child Care",
      address: "2200 Tenth Line Rd",
      city: "Ottawa",
      postalCode: "K4A 0X4",
      phone: "613-555-0207",
      website: "https://example.org/orleans-child-care",
      latitude: 45.4546,
      longitude: -75.4858,
    },
    {
      name: "Riverbend Seniors Hub",
      category: "Seniors",
      address: "850 Riverside Dr",
      city: "Ottawa",
      postalCode: "K1S 5L2",
      phone: "613-555-0208",
      website: "https://example.org/riverbend-seniors",
      latitude: 45.402,
      longitude: -75.684,
    },

    // Hamilton
    {
      name: "Hamilton Community Health Services",
      category: "Health",
      address: "100 Main St W",
      city: "Hamilton",
      postalCode: "L8P 1H6",
      phone: "905-555-0301",
      website: "https://example.org/hamilton-health",
      latitude: 43.2557,
      longitude: -79.8711,
    },
    {
      name: "James Street Mental Health Resource Centre",
      category: "Mental Health",
      address: "250 James St N",
      city: "Hamilton",
      postalCode: "L8R 2L3",
      phone: "905-555-0302",
      website: "https://example.org/james-mental-health",
      latitude: 43.2649,
      longitude: -79.8663,
    },
    {
      name: "Mountainview Family Shelter",
      category: "Shelter",
      address: "40 Upper James St",
      city: "Hamilton",
      postalCode: "L9C 1X2",
      phone: "905-555-0303",
      website: "https://example.org/mountainview-shelter",
      latitude: 43.243,
      longitude: -79.884,
    },
    {
      name: "Hamilton Community Food Share",
      category: "Food Bank",
      address: "15 Barton St E",
      city: "Hamilton",
      postalCode: "L8L 2V6",
      phone: "905-555-0304",
      website: "https://example.org/hamilton-food-share",
      latitude: 43.2645,
      longitude: -79.8628,
    },
    {
      name: "Hamilton Newcomer Settlement Centre",
      category: "Settlement",
      address: "780 Upper Wentworth St",
      city: "Hamilton",
      postalCode: "L9A 4V7",
      phone: "905-555-0305",
      website: "https://example.org/hamilton-settlement",
      latitude: 43.2218,
      longitude: -79.8574,
    },

    // Smaller centres to fill out the map
    {
      name: "Peel Community Employment Services",
      category: "Employment",
      address: "151 City Centre Dr",
      city: "Mississauga",
      postalCode: "L5B 1M7",
      phone: "905-555-0401",
      website: "https://example.org/peel-employment",
      latitude: 43.589,
      longitude: -79.6441,
    },
    {
      name: "York Region Community Legal Clinic",
      category: "Legal",
      address: "10 Highway 7 E",
      city: "Richmond Hill",
      postalCode: "L4B 3Z4",
      phone: "905-555-0402",
      website: "https://example.org/york-legal",
      latitude: 43.8437,
      longitude: -79.3812,
    },
    {
      name: "Waterloo Region Settlement Services",
      category: "Settlement",
      address: "150 Frederick St",
      city: "Kitchener",
      postalCode: "N2H 2M2",
      phone: "519-555-0403",
      website: "https://example.org/waterloo-settlement",
      latitude: 43.4503,
      longitude: -80.486,
    },
    {
      name: "Downtown Guelph Community Centre",
      category: "Community Centre",
      address: "20 Carden St",
      city: "Guelph",
      postalCode: "N1H 3A2",
      phone: "519-555-0404",
      website: "https://example.org/guelph-community",
      latitude: 43.5448,
      longitude: -80.249,
    },
    {
      name: "Niagara North Seniors Activity Centre",
      category: "Seniors",
      address: "25 Queen St",
      city: "St. Catharines",
      postalCode: "L2R 3G4",
      phone: "905-555-0405",
      website: "https://example.org/niagara-seniors",
      latitude: 43.1594,
      longitude: -79.2469,
    },
    {
      name: "Thunder Bay Community Health and Wellness",
      category: "Health",
      address: "200 Red River Rd",
      city: "Thunder Bay",
      postalCode: "P7B 1A4",
      phone: "807-555-0406",
      website: "https://example.org/thunderbay-health",
      latitude: 48.4333,
      longitude: -89.22,
    },
  ];

  for (const service of services) {
    await prisma.service.create({ data: service });
  }

  console.log(`Inserted ${services.length} services.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
